#!/bin/bash

export TW_DEFAULT_LANGUAGE="en"
export LC_ALL="C"

export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1

export FOX_BUILD_TYPE="Unofficial"
export OF_MAINTAINER="Shas45558"
export FOX_MAINTAINER_PATCH_VERSION="1"

# Screen
export OF_SCREEN_H=2340
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_ALLOW_DISABLE_NAVBAR=0

# Android 13 / MT6768
export OF_DEFAULT_KEYMASTER_VERSION=4.1
export OF_PATCH_AVB20=1
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
export OF_USE_SYSTEM_FINGERPRINT=1
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1

add_lunch_combo twrp_lancelot-ap2a-eng
add_lunch_combo twrp_merlinx-ap2a-eng
